### ISSUE TITLE
Have you tried VGG features?

### ISSUE THREAD

**Issue by cloud-waiting-for-wind** [jnhwkim/MulLowBiVQA#1]
Hi, nice job!
Compare with Resnet , how many percentage  points it will be lower if I use VGG features?
Have you tried VGG features?

**Comment by jnhwkim** [comment]
In our [previous work](https://papers.nips.cc/paper/6446-multimodal-residual-learning-for-visual-qa), we compared. But I didn't in this work. Since ResNet feature seems to obviously show the better performance, at least in visual question answering task (for survey, [Wu et al., 2016](https://arxiv.org/abs/1607.05910)). 
If you want my mystic hunch ;-), around 1% is expected.

**Comment by cloud-waiting-for-wind** [comment]
haha  ;-) 
Thanks.
