### ISSUE TITLE
 A few questions

### ISSUE THREAD

**Issue by cloud-waiting-for-wind** [jnhwkim/MulLowBiVQA#2]
I’m sorry to bother you again..... I have a few questions
1.
I notice that you use GRU to process questions in your previous work(Kim et al., 2016b) and this paper. 
you have implemented the code of LSTM in this work(  elseif opt.rnn_model == 'LSTM' then....)
So, why do you choose GRU finally?  how many percentage points it will be lower if I use LSTM?

2 .  in train.lua  
require 'netdef.MRN'  ,but there is no MRN.lua file

3 should  I use L2-normalization　in　prepro_res.lua ？
thanks!

**Comment by jnhwkim** [comment]
1. The choice of question embedding model is explored in a preliminary experiment. I remember that less than 0.5%, not for sure. However, there is a result that Noh et al. (2016) prefer 2-LSTM instead of GRU of ours (which is from Noh et al., 2015). So, it seems somewhat controversial.
2. I fixed this. Thanks!
3. I didn't use that in the paper. But I checked. It does not help to significantly improve the result in our case.
